services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Pass@word123"
      ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
        - "1434:1434"